# Generated by Django 4.1.3 on 2022-11-19 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "DRIVER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("level", "branch"), name="unique_grade_level_and_branch"
            ),
        ),
    ]
