# Generated by Django 4.1.3 on 2022-12-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="version",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
