# Generated by Django 4.1.4 on 2022-12-12 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendance_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="bus",
        ),
    ]
