# Generated by Django 4.1.4 on 2022-12-13 02:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_busmember_finished_at_busmember_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="busmember",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="busmember",
            name="finished_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="busmember",
            name="started_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
