# Generated by Django 4.1.4 on 2022-12-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0005_busmember_created_at_alter_busmember_finished_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="num_absent_student",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="num_total_student",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
