# Generated by Django 4.1.4 on 2022-12-12 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_busmember_started_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="busmember",
            name="started_at",
        ),
        migrations.AddField(
            model_name="busmember",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
