# Generated by Django 4.1.4 on 2022-12-12 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_remove_busmember_started_at_busmember_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="busmember",
            name="started_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
