# Generated by Django 4.1.4 on 2022-12-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_attendance_num_absent_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="num_absent_student",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
