# Generated by Django 4.1.4 on 2022-12-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_alter_attendance_num_absent_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="busmember",
            old_name="finished_at",
            new_name="finish_date",
        ),
        migrations.RenameField(
            model_name="busmember",
            old_name="started_at",
            new_name="start_date",
        ),
    ]
