# Generated by Django 4.1.4 on 2022-12-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_rename_finished_at_busmember_finish_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("present", models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                "ordering": ["-attendance"],
            },
        ),
        migrations.RenameModel(
            old_name="Village",
            new_name="Destination",
        ),
        migrations.RemoveField(
            model_name="busmember",
            name="bus",
        ),
        migrations.RemoveField(
            model_name="busmember",
            name="school",
        ),
        migrations.RemoveField(
            model_name="busmember",
            name="student",
        ),
        migrations.RemoveField(
            model_name="district",
            name="city",
        ),
        migrations.AlterModelOptions(
            name="school",
            options={},
        ),
        migrations.RenameField(
            model_name="bus",
            old_name="village",
            new_name="destinations",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="num_absent_student",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="num_total_student",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="version",
        ),
        migrations.RemoveField(
            model_name="school",
            name="address_detail",
        ),
        migrations.RemoveField(
            model_name="school",
            name="city",
        ),
        migrations.RemoveField(
            model_name="school",
            name="district",
        ),
        migrations.RemoveField(
            model_name="school",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="student",
            name="village",
        ),
        migrations.AddField(
            model_name="student",
            name="bus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.bus",
            ),
        ),
        migrations.DeleteModel(
            name="AbsentStudent",
        ),
        migrations.DeleteModel(
            name="BusMember",
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="District",
        ),
        migrations.AddField(
            model_name="studentstatus",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance.attendance"
            ),
        ),
        migrations.AddField(
            model_name="studentstatus",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance.student"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentstatus",
            constraint=models.UniqueConstraint(
                fields=("attendance", "student"),
                name="unique_student_with_student_and_attendance",
            ),
        ),
    ]
