# Generated by Django 4.1.4 on 2022-12-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_studentstatus_rename_village_destination_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentStatus",
            new_name="StudentAttendance",
        ),
        migrations.AlterModelOptions(
            name="studentattendance",
            options={
                "ordering": ["-attendance"],
                "verbose_name_plural": "studentstatus",
            },
        ),
    ]
