# Generated by Django 4.1.4 on 2022-12-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_rename_studentstatus_studentattendance_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentattendance",
            options={"ordering": ["-attendance"]},
        ),
    ]
