# Generated by Django 4.1.5 on 2023-01-13 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0011_alter_studentattendance_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="grade",
            name="unique_grade_level_and_branch",
        ),
        migrations.AlterField(
            model_name="student",
            name="bus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.bus",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="present",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.UniqueConstraint(
                fields=("school", "level", "branch"),
                name="unique_grade_school_level_and_branch",
            ),
        ),
    ]
