# Generated by Django 4.1.5 on 2023-01-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0012_remove_grade_unique_grade_level_and_branch_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bus",
            options={"ordering": ["bus_number"], "verbose_name_plural": "busses"},
        ),
        migrations.AlterModelOptions(
            name="school",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="school",
            name="code",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name="bus",
            constraint=models.UniqueConstraint(
                fields=("bus_number",), name="unique_bus_number"
            ),
        ),
    ]
